-- Create a table for storing student performance predictions
create table predictions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_name text,
  study_hours numeric not null,
  attendance numeric not null,
  prev_score numeric not null,
  predicted_score numeric not null
);

-- Output usage example
-- To run this, go to Supabase Dashboard -> SQL Editor and paste this content.
